### ISSUE TITLE
заполнить install.inf как в норм.плагинах, в том числе homepage=

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_navbar#1]

**Comment by ahreenah** [comment]
fixed

**Comment by Alexey-T** [comment]
поправить-

title=HTML Navigation Bar
desc=In HTML files, plugin shows navigational breadcrumb bar on the top
type=cudatext-plugin
subdir=cuda_html_navbar

**Comment by Alexey-T** [comment]
not fixed. см мой комент
