### ISSUE TITLE
встроить тулбар внуть едитора, как я советовал в репо Куды

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_navbar#14]
поставь Куд 1.79.2

**Comment by ahreenah** [comment]
![image](https://user-images.githubusercontent.com/38169798/57044431-3784ce00-6c73-11e9-99f8-135a07d95627.png)
Поставил - всё равно не работает

**Comment by Alexey-T** [comment]
в версии 1.79.2 мой пример отсюда работает?
https://github.com/Alexey-T/CudaText/issues/1993

**Comment by ahreenah** [comment]
поправил, но оно теперь поверх части редактора

**Comment by Alexey-T** [comment]
Не поправил - ты взял не то слово, надо prop_handle_parent
