### ISSUE TITLE
кривое имя плагина в Settings-plugins

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_navbar#18]
надо полное имя

**Comment by ahreenah** [comment]
![image](https://user-images.githubusercontent.com/38169798/57144587-079c0e80-6dca-11e9-89f9-5f764b142666.png)

**Comment by Alexey-T** [comment]
Полное имя плагина html navigation bar

**Comment by Alexey-T** [comment]
не поправил -надо красиво- `HTML Navigation Bar`
