### ISSUE TITLE
красить тулбар как в текущ.теме Куды, например в теме sub

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_navbar#2]

**Comment by ahreenah** [comment]
поправил тему кнопок, но не понимаю, как поправить тему фона

**Comment by Alexey-T** [comment]
app_proc() с акшеном таким PROC_THEME_UI_DATA_GET
http://wiki.freepascal.org/CudaText_API#Themes

получишь dict, в нем найдешь элемент про "фон тулбара", его применишь на "color" панели.
