### ISSUE TITLE
зачем читать строку в callback?

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_navbar#27]
```
        def callbackf():
            try:
                self.need_action=False
                coord=self.cors[count-1]
                line=ed.get_text_line(coord[0])
```

**Comment by ahreenah** [comment]
new_x=coord[1]
while new_x>0:
if line[new_x]=='<':
break
new_x-=1
new_x+=1
ed.set_caret(new_x,coord[0])

**Comment by ahreenah** [comment]
new_x=coord[1]
while new_x>0:
if line[new_x]=='<':
break
new_x-=1
new_x+=1
ed.set_caret(new_x,coord[0])

**Comment by ahreenah** [comment]
она же используется
