### ISSUE TITLE
создавать кнопки 1 раз

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_navbar#30]
идейка. создавать кнопки только 1 раз. потом только менять их text.
если создано 3 кнопки, на след.раз надо 5, то дополнительно создашь 2 кнопки.
если потом надо 2, то спрячешь последние 3 (visible=False)

**Comment by ahreenah** [comment]
посмотрите код плз - ошибка в колбеках?

**Comment by Alexey-T** [comment]
сори, занят.
