### ISSUE TITLE
авто-показывать плаг только в HTML files

### ISSUE THREAD

**Issue by Alexey-T** [medvosa/cuda_html_navbar#6]
надо детектить лексер- ed.get_prop(PROP_LEXER_FILE,'')
и показать панель только если это один из нужных лексов.

список лексов дать по опции.
cuda_html_navbar.ini, в нем опцию 

[op]
lexers=HTML,HTML Diafan

comma separated lexers list. дефолт опции - показал.

**Comment by ahreenah** [comment]
fixed.
Config file should have following path: "...CudaText/config/cuda_html_navbar.ini"

**Comment by Alexey-T** [comment]
юзер не знает какой файл-- надо дать команду в Options / Settings-plugins / HTML Navigation Bar / Config
которая откроет файл конфига

как это делать- смотри в py/cuda_addonman/install.inf
